Systems system improvements
Battle-Brothers-Legends/mod_MSU pull request #25
Opened 2022-02-14 23:24 UTC by Enduriel

Splits up Debug into two parts (the Log System and the static functions in Debug).
Changes Systems to require each mod to register with each system it wants to use.
Improves ModSettings handling of long mod names with a custom button.

2022-02-15 00:40 UTC, LordMidas requested changes
I will have to look deeper and then I'll give my thoughts on how we want to name the Debug/Logging system and where the static utility functions should be. It seems to me that the system should be called Debug, as it has room for expansion. If we call it Log system then it is very restricted.

2022-02-15 00:40 UTC, LordMidas commented on scripts/!mods_preload/msu_aa.nut
> +	this.MSU.registerMod(MSUModName, "0.6.27", "Modding Standards and Utils");
I would like the name to be written as "Modding Standards & Utilities"

2022-02-15 00:40 UTC, LordMidas commented on MSU-Documentation.md
> +- `this.MSU.Systems.Log.printStackTrace( _maxDepth = 0, _maxLen = 10, _advanced = false )`
This isn't correct. The printStackTrace function is currently in `this.MSU.Debug` on your branch

2022-02-15 00:40 UTC, LordMidas commented on scripts/!mods_preload/msu_debug.nut
> +	::isDebugEnabled <- function(_modID, _flagID = this.MSU.Systems.Log.DefaultFlag){
If we are going with `this.MSU.Systems.Log` then the name of the shortcut needs to be updated perhaps to something like ``::isLogEnabled`

2022-02-23 21:55 UTC, TaroEld approved these changes

2022-02-24 02:05 UTC, merged