MSU.Error and refactor code accordingly
Battle-Brothers-Legends/mod_MSU pull request #78
Opened 2022-03-23 00:46 UTC by LordMidas

This accomplishes two things:

1. Keeps true Exceptions separate from info-containing Error messages.
2. Avoids copy pasting strings, as Error messages are contained in MSU.Error and we only need to edit them at one place if we want to change something.

Currently it requires two lines of code wherever you wanna throw an error and exception:
```
::logError(MSU.Exception.ModNotRegistered(_key);
throw ::MSU.Exception.KeyNotFound(_key);
```

An alternative method could be to implement a `::MSU.exceptionWithError( _exception, _error = null )` function and use it as such:
```
throw ::MSU.exceptionWithError(::MSU.Exception.KeyNotFound(_key), ::MSU.Error.ModNotRegistered(_key))
```
Let me know what you guys prefer.

2022-03-23 07:50 UTC, TaroEld approved these changes
I do prefer the way it is in this PR, keeps things nice and separate.

2022-03-26 14:58 UTC, Enduriel commented
I like this, but the terminology seems to be misleading. I'd prefer something like `::MSU.ExceptionInfo` for the additional information.

2022-03-26 14:59 UTC, Enduriel requested changes
I like this, but the terminology seems to be misleading. I'd prefer something like `::MSU.ExceptionInfo` for the additional information.

2022-03-26 19:28 UTC, LordMidas commented
> I like this, but the terminology seems to be misleading. I'd prefer something like `::MSU.ExceptionInfo` for the additional information.

If we are going with the 2-line method then `::MSU.Error` is better imo as it is printed via `::logError` and its only job is to serve as a repository of frequently thrown errors.

2022-03-31 14:53 UTC, Enduriel commented
Ya okay, it's not a big deal anyway.

2022-04-01 02:34 UTC, merged